packages:
  - apps/*
  - packages/*
  - packages/*/*

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true

catalog:
  '@better-auth/drizzle-adapter': 1.6.11
  '@better-auth/expo': 1.6.11
  '@better-auth/passkey': 1.6.11
  '@inlang/paraglide-js': 2.18.2
  '@mdx-js/react': 3.1.1
  '@mdx-js/rollup': 3.1.1
  '@react-email/components': ^1.0.0
  '@types/mdx': 2.0.13
  '@types/node': ^22.13.14
  '@types/react': ^19.2.15
  '@types/react-dom': ^19.2.3
  aws4fetch: 1.0.20
  better-auth: 1.6.11
  dotenv: ^17.2.2
  envin: ^1.2.0
  hono: ^4.12.27
  lucide-react: ^0.546.0
  mysql2: ^3.14.0
  next-themes: ^0.4.6
  postgres: ^3.4.7
  react: ^19.2.7
  react-dom: ^19.2.7
  simple-flakeid: ^0.0.5
  stripe: ^18.5.0
  typescript: ^6
  uuid: ^13.0.0
  zod: ^4.1.13

onlyBuiltDependencies: '["esbuild","msw","sharp","workerd","electron","@tarojs/binding","@tarojs/cli","core-js","core-js-pure"]'
